### ISSUE TITLE
d0reader deployment

### ISSUE THREAD

**Issue by ffaerber** [buzzn/d0-reader#12]
auto deploy new version of d0-reader.
https://github.com/CenturyLinkLabs/watchtower

**Comment by ffaerber** [comment]
deploying running d0reader is very risky.
this needs to be tested very well

**Comment by drthth** [comment]
the d0-reader connection to staging is broken. I think we need urgently a working plattform for the reader, to continue the field test. Better is staging.buzzn.net.
