### ISSUE TITLE
Negative values at d0-reader do not work

### ISSUE THREAD

**Issue by drthth** [buzzn/d0-reader#13]

**Comment by ffaerber** [comment]
I do not understand this ticket

**Comment by drthth** [comment]
look here: https://staging.buzzn.net/metering_points/a6b03387-a3a2-4ad6-b9cd-fdaed86c8fb8 on live view

**Comment by ffaerber** [comment]
is the smartmeter valid connected?

**Comment by drthth** [comment]
Yes! It is sending the following JSON (this example is failed, but it is sending the same JSON without failed, too):

{
"id": "4089",
"type": "sml",
-"data": {
"sml": "\r\n/ESY5Q3DA1004 V3.02\r\n\r\n1-0:0.0.0_255(1003003416)\r\n1-0:1.8.0_255(00000000.9000000_kWh)\r\n1-0:21.7.255_255(000000.00_W)\r\n1-0:41.7.255_255(-000116.85_W)\r\n1-0:61.7.255_255(000000.00_W)\r\n1-0:1.7.255_255(-000116.85_W)\r\n1-0:96.5.5_255(D2)\r\n0-0:96.1.255*255(1ESY1003003416)\r\n"
},
"priority": 0,
"progress": 0,
"state": "failed",
"error": "undefined",
"created_at": "1469791135752",
"promote_at": "1469791135752",
"updated_at": "1469791136018",
"failed_at": "1469791136018",
"started_at": "1469791135767",
"workerId": "kue:30959b5a10a8:1:sml:1",
-"attempts": {
"made": 1,
"remaining": 0,
"max": 1
},
"active": true
}

**Comment by ffaerber** [comment]
can you add your SML so i can wride a test for it

**Comment by drthth** [comment]
It is always the same. Thats the Easymeter I used since 5 years. SML is like this:
https://github.com/buzzn/d0-reader/blob/master/sml_info/easymeter.txt

**Comment by ffaerber** [comment]
this file contains multible SMLs. which line?

**Comment by ffaerber** [comment]
i see in you error json.
0:41.7.255255(-000116.85W)
0:1.7.255255(-000116.85W)
do you have a two ways out_out meter ?

**Comment by drthth** [comment]
For some reason I dont know the value is always negative. No, it is an one direction meter only.

**Comment by ffaerber** [comment]
i need your SML to test this

**Comment by drthth** [comment]
Finally I found it here:
https://github.com/buzzn/d0-reader/commit/697da25c736fd970d79bec4637e9a44d4c2029be

+/ESY5Q3DA1004 V3.02
 +
 +1-0:0.0.0_255(1003003416)
 +1-0:1.8.0_255(00000000.9000000_kWh)
 +1-0:21.7.255_255(000000.00_W)
 +1-0:41.7.255_255(-000008.82_W)
 +1-0:61.7.255_255(000000.00_W)
 +1-0:1.7.255_255(-000008.82_W)
 +1-0:96.5.5_255(D2)
 +0-0:96.1.255*255(1ESY1003003416)
 +!
 +

**Comment by ffaerber** [comment]
you can test it with this file
https://github.com/buzzn/d0-reader/blob/master/test/sml_parser.js
add your sml to it and exept your results.
https://github.com/buzzn/d0-reader/blob/master/test/sml_parser.js#L24-L31

**Comment by ffaerber** [comment]
if you push 
the test will run

**Comment by ffaerber** [comment]
if the test is ok the codeship button is grean.
https://github.com/buzzn/d0-reader/blob/master/README.md

**Comment by drthth** [comment]
can you show me how to do this?

**Comment by ffaerber** [comment]
duplicate this
https://github.com/buzzn/d0-reader/blob/master/test/sml_parser.js#L7-L32
change this sml to your sml.
change tests https://github.com/buzzn/d0-reader/blob/master/test/sml_parser.js#L24-L31
and push to github or run npm test local.

**Comment by ffaerber** [comment]
no anser. delete
