### ISSUE TITLE
reset/logout D0-Reader

### ISSUE THREAD

**Issue by ffaerber** [buzzn/d0-reader#15]

**Comment by ChriWiChris** [comment]
What does this ticket stand for? Could you please give a description?

**Comment by ffaerber** [comment]
German: in den werkszustand zurücksetzen.

**Comment by ffaerber** [comment]
fix #23

**Comment by ffaerber** [comment]
connect #23

**Comment by drthth** [comment]
Wie geht der Reset? Muss der ZP gelöscht sein?
