### ISSUE TITLE
hager meter does not work

### ISSUE THREAD

**Issue by drthth** [buzzn/d0-reader#17]
using the hager meter does not work, it seems that the d0-Reader does not parse the SML correctly. Its SML is here: https://github.com/buzzn/d0-reader/blob/master/sml_info/hager_ehz.sml

**Comment by ffaerber** [comment]
this is the test for the hager ehz.
https://github.com/buzzn/d0-reader/blob/master/test/sml_parser.js#L250-L285
is the test wrong @drthth ?

**Comment by ffaerber** [comment]
this is what i expect from the parser.
https://github.com/buzzn/d0-reader/blob/master/test/sml_parser.js#L277-L284

**Comment by ffaerber** [comment]
@drthth  can i delete this ticket?

**Comment by ffaerber** [comment]
no answer. i close this ticket
