### ISSUE TITLE
GL research

### ISSUE THREAD

**Issue by ffaerber** [buzzn/d0-reader#31]
Includes:
- sending of MQTT message from D0-reader (respberryPi proto)
- setup of MQTT broker with topic
- setup of MQTT client to subscribe to MQTT topic
- parsing of MQTT message and storage in new mongo DB

**Comment by dottorer** [comment]
@ffaerber See https://buzzn-team.atlassian.net/wiki/display/DEV/Project%3A+d0-reader+with+UCM+by+GL-Solutions#Project:d0-readerwithUCMbyGL-Solutions-Messageformats for first details on message formats.

**Comment by dottorer** [comment]
This prototype includes:
- d0 optical header on Raspberry sends MQTT to broker
- MQTT broker with topic receives messages
- MQTT listener receives messages, parses and stores in MongoDB
- readings stored in DB can be retrieved with meter id

All of this runs in DigitalOcean, deployment fully dockerized.

**Comment by ffaerber** [comment]
in action to find here: https://metering.buzzn.io/meters/60328159
this is not super stable. i think this is the public mqtt broker.
so next step should be to install the mqtt broker on docker/DigitalOcean
